events {}
http {
  resolver 127.0.0.11 valid=5s;
  include /etc/nginx/mime.types;
  server {
    listen 80;
    client_max_body_size 50M;
    root /usr/share/nginx/html;
    index index.html;
    location / {
      try_files $uri $uri/ /index.html;
    }
    location /api/ {
      proxy_pass http://REPLACE_WITH_ALB_DNS:80;
    }
    location /uploads/ {
      proxy_pass http://REPLACE_WITH_ALB_DNS:80;
    }
  }
}
