events {}
http {
  resolver 127.0.0.11 valid=5s;
  include /etc/nginx/mime.types;
  server {
    listen 80;
    client_max_body_size 50M;
    root /usr/share/nginx/html;
    index index.html;
    location / {
      try_files $uri $uri/ /index.html;
    }
    location ~ ^/api/(properties|search|reviews) {
      set $upstream_property property-service;
      proxy_pass http://$upstream_property:8001;
    }
    location /uploads {
      set $upstream_property property-service;
      proxy_pass http://$upstream_property:8001;
    }
    location ~ ^/api/ai {
      set $upstream_ai ai-service;
      proxy_pass http://$upstream_ai:8003;
    }
    location ~ ^/api/(auth|users|bookings) {
      set $upstream_booking booking-service;
      proxy_pass http://$upstream_booking:8002;
    }
  }
}
